
# 动画模式
# cycle：正序播放，到最后一个后回到第一个（默认）
# random：随机播放
# pingpong：往返循环，在正序和倒序之间来回切换，播放到最后一个后会倒回第一个
# reverse：倒序播放，和正序相同，不过是从最后一个开始

# 变量格式
# %animpapi_自定义名称%

# 主键，禁止修改
placeholders:
  # 自定义名称
  cycle:
    # 动画模式
    type: "cycle"
    # 间隔延迟，单位：毫秒
    speed: 100
    # 文本内容，支持papi变量
    text:
      - "&a欢&f迎来到服务器"
      - "&a欢迎&f来到服务器"
      - "&a欢迎来&f到服务器"
      - "&a欢迎来到&f服务器"
      - "&a欢迎来到服&f务器"
      - "&a欢迎来到服务&f器"
      - "&a欢迎来到服务器"
  pingpong:
    type: "pingpong"
    speed: 50
    text:
      - "&c=="
      - "&c===="
      - "&c======"
      - "&c========"
      - "&c=========="
      - "&c============"
  random:
    type: "random"
    speed: 50
    text:
      - "&c随机选择"
      - "&a随机选择"
      - "&e随机选择"
      - "&b随机选择"
      - "&d随机选择"